act_fun: QGateGrad
adam_epoch: 1000
batch_size: 16
clip_grad: null
cooldown_epochs: 10
cut_mix: false
cutmix_beta: 1.0
cutmix_noise: 0.0
cutmix_num: 1
cutmix_prob: 0.5
dataset: tinyimagenet
decay_epochs: 30
decay_rate: 0.1
device: 0
encode: direct
epochs: 600
eval_metric: top1
event_mix: false
event_size: 48
layer_by_layer: false
log_interval: 25
loss_fn: ce
lr: 0.01
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
min_lr: 1.0e-05
mix_up: false
model: cifar_convnet
momentum: 0.9
n_warm_up: 0
node_resume: ''
node_trainable: false
node_type: LIFNode
noisy_grad: 0.0
num_classes: 200
opt: adamw
opt_betas: null
opt_eps: 1.0e-08
output: ./outputtry
patience_epochs: 10
power: 1
rand_aug: false
randaug_m: 15
randaug_n: 3
recovery_interval: 0
resume: ''
sched: cosine
seed: 0
spike_output: false
spike_rate: false
start_epoch: null
step: 4
suffix: ''
task_num: 40
tau: 2.0
temporal_flatten: false
thresh: 0.5
train_portion: 0.9
visualize: false
warmup_epochs: 5
warmup_lr: 0.0001
weight_decay: 0.01
workers: 4
